name: Build and push to GKE
on: 
  [push,repository_dispatch]

env:
  PROJECT_ID: ${{secrets.GKE_PROJECT}}
  GKE_CLUSTER: test-gke2
  GKE_ZONE: us-west1-b 
  DEPLOYMENT_NAME: bridge-sever
  IMAGE: prediction_model
  TAG: 1.0.0

jobs:
  setup-build-publih-deploy:
    name: Setup Build Publish Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up Google Cloud CLI 
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@0.1.3
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        with:
          service_account_key: ${{secrets.GKE_SA_KEY}}
          project_id: ${{secrets.GKE_PROJECT}}

      - name: Configure Docker
        run: |-
          gcloud --quiet auth configure-docker
      
      - name: get GKE Credentials
        run: |-
          gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"

      - name: Build Docker Image for prediction 
        run:  |-
          docker build ./model/ --tag "gcr.io/$PROJECT_ID/$IMAGE:$TAG"
          docker build --build-arg Bearer=${{secrets.NEW_GITHUB_TOKEN_for_kubernetes_test}} ./bridge_server/ --tag "gcr.io/$PROJECT_ID/bridge_server:0.0.1"
      - name: Publish Docker Image to GCR 
        run: |-
          docker push "gcr.io/$PROJECT_ID/$IMAGE:$TAG"
          docker push "gcr.io/$PROJECT_ID/bridge_server:0.0.1"
      - name: Set up Kustomize
        run: |-
          curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
          chmod u+x ./kustomize

      - name: Deploy Image to GKE cluster
        run: |-
          ./kustomize edit set image gcr.io/PROJECT_ID/bridge_server:0.0.1=gcr.io/$PROJECT_ID/bridge_server:0.0.1
          ./kustomize build . | kubectl apply -f -
          kubectl rollout status deployment/$DEPLOYMENT_NAME
          kubectl get services -o wide


        
